import { FaCheckCircle, FaTimesCircle } from "react-icons/fa";
import { AiOutlineCalendar } from "react-icons/ai";
import { HiOutlineDocumentText } from "react-icons/hi";

import React from "react";

const ListComponent = () => {
  return (
   <section className="w-full py-16 px-4 sm:px-8 md:px-16 lg:px-24 bg-white text-gray-800">
  <div className="max-w-5xl mx-auto">
    <h2 className="text-3xl md:text-4xl font-bold text-center mb-6 text-[#1a1a1a]">
      TAN Registration Number
    </h2>

    <p className="text-center text-base md:text-lg mb-10 text-gray-600">
      TAN (Tax Deduction and Collection Account Number) is a unique 10-digit alphanumeric code 
      allotted by the Income Tax Department. It is mandatory for all persons and entities responsible 
      for deducting or collecting taxes at source.
    </p>

    <div className="grid gap-6 md:grid-cols-2">
      {/* Left - TAN Number Format */}
      <div className="bg-white p-6 rounded-xl shadow-md border border-[#b44593]/50 space-y-4 hover:scale-[1.02] hover:shadow-lg transition-all duration-300">
        <h3 className="text-lg font-semibold text-[#1a1a1a]">TAN Number Format & Structure</h3>
        <ul className="space-y-4">
          {[
            "First 4 Characters (Alphabets): First three letters represent jurisdiction, and the fourth represents applicant’s name.",
            "Next 5 Characters (Numbers): Unique system-generated digits.",
            "Last Character (Alphabet): A unique letter generated by the system.",
            "Example: ABCD12345E",
          ].map((item, idx) => (
            <li key={idx} className="flex items-start gap-3 text-sm md:text-base text-[#1a1a1a]">
              <FaCheckCircle className="text-[#790046] m-1 text-lg" />
              <span className="w-[90%]">{item}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Right - Who Needs TAN */}
      <div className="bg-white p-6 rounded-xl shadow-md border border-[#b44593]/50 space-y-6 hover:scale-[1.02] hover:shadow-lg transition-all duration-300">
        <h3 className="text-lg font-semibold text-[#1a1a1a]">Who Needs a TAN?</h3>
        <ul className="space-y-4">
          {[
            "Businesses & Companies – Making TDS deductions on salaries, rent, contractor payments, commission, or professional fees.",
            "Non-Profit Organizations – Required if making payments beyond specified thresholds.",
            "Branches of Companies – Each branch making specified payments must apply for TAN separately.",
            "Proprietorship Firms – Individual proprietors must apply for TAN if liable to deduct TDS.",
          ].map((item, idx) => (
            <li key={idx} className="flex items-start gap-3 text-sm md:text-base text-[#1a1a1a]">
              <FaCheckCircle className="text-[#790046] m-1 text-lg" />
              <span className="w-[90%]">{item}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>

    {/* Note */}
    <p className="text-center text-base md:text-lg mt-10 text-gray-600 italic">
      <span className="font-bold">Note: </span> Salaried individuals not required to deduct TDS do not need a TAN.
    </p>
  </div>
</section>

  );
};

export default ListComponent;
