
import '@/utils/disableConsoleInProd';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Preloader from './Components/Preloader';
import ClientLayoutWrapper from './Components/ClientLayoutWrapper';
import TopMarqueeWrapper from './Components/TopMarquee/TopMarqueeWrapper';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Delfyle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Delfyle</title>
        <link rel="icon" href="/delfyle-logo/favicon.png" type="image/png" />
      </head>
      <body className={inter.className}>
        <Preloader />
        <TopMarqueeWrapper/>
        <ClientLayoutWrapper>
          {children}
        </ClientLayoutWrapper>
        <div id="portal"></div>
      </body>
    </html>
  );
}
